services:
  app:
    build: .
    container_name: meanrsi_app
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///data/signals.db}
    volumes:
      - ./data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  dashboard:
    build: .
    container_name: meanrsi_dashboard
    command: streamlit run src/dashboard.py --server.port=8501 --server.address=0.0.0.0
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///data/signals.db}
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    depends_on:
      - app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
